# Getting Started with NumPy - Lab

## Introduction

Now that we have introduced NumPy, let's put it to practice. In this lab, you are going to be creating arrays, performing operations on them, and returning new arrays all using the NumPy library. Let's get started!

## Objectives

You will be able to: 

- Instantiate a numpy array with specified values 
- Use broadcasting to perform a math operation on an entire numpy array 


## Import `NumPy` under the standard alias

In [1]:
# Import numpy using the standard alias
import numpy as np


## Generate some mock data

Create a NumPy array for each of the following:
    1. Using a range
    2. Using a Python list
    
Below, create a list in Python that has 5 elements (i.e. [0,1,2,3,4]) and assign it to the variable `py_list`. 

Next, do the same, but instead of a list, create a range with 5 elements and assign it to the variable, `py_range`.

Finally, use the list and range to create NumPy arrays and assign the array from list to the variable `array_from_list`, and the array from the range to the variable `array_from_range`.

In [7]:
py_range = range(0,5)

In [11]:
py_list =[0,1,2,3,4]

In [14]:
# Your code here
py_list = [0,1,2,3,4]
py_range = range(0,5)
array_from_list = np.array(py_list)
array_from_list = np.array(py_range)
print(array_from_list, array_from_list)

[0 1 2 3 4] [0 1 2 3 4]


Next, we have a list of heights and weights and we'd like to use them to create a collection of BMIs. However, they are both in inches and pounds (imperial system), respectively. 

Let's use what we know to create NumPy arrays with the metric equivalent values (height in meters & weight in kg).

> **Remember:** *NumPy can make these calculations a lot easier and with less code than a list!*

> 1.0 inch = 0.0254 meters

> 2.2046 lbs = 1 kilogram

In [15]:
# Use the conversion rate for turning height in inches to meters
list_height_inches = [65, 68, 73, 75, 78]

# Your code here
array_height_inches = np.array(list_height_inches)
#multiply the array by 0.0254 then divide by 1.0 .
array_height_meters = np.divide(np.multiply(np.array(list_height_inches),0.0254),1.0)
array_height_meters
     #expected results [1.651, 1.7272, 1.8542, 1.905 , 1.9812]

array([1.651 , 1.7272, 1.8542, 1.905 , 1.9812])

In [16]:
# Use the conversion rate for turning weight in pounds to kilograms
list_weight_pounds = [150, 140, 220, 205, 265]

# Your code here
array_weight_pounds = np.array(list_weight_pounds )
#multiply the array by 1 then divide by 2.2046.
array_weight_kg = np.divide(np.multiply( np.array(list_weight_pounds ),1),2.2046)
array_weight_kg# expected result [ 68.04,  63.5 ,  99.79,  92.99, 120.2 ] 

array([ 68.03955366,  63.50358342,  99.79134537,  92.98739   ,
       120.20321147])

The metric formula for calculating BMI is as follows:

> BMI = weight (kg) ÷ height^2 (m^2)

So, to get BMI we divide weight by the squared value of height. For example, if I weighed 130kg and was 1.9 meters tall, the calculation would look like:

> BMI = 130 / (1.9*1.9)

Use the BMI calculation to create a NumPy array of BMIs

In [17]:
# Your code here
# square the height array list
squared_height_array = np.power(array_height_meters ,2)
#so divide the weight with the  squared height
BMI_array = array_weight_kg /squared_height_array
BMI_array            #expected results([24.9613063 , 21.28692715, 29.02550097, 25.62324316, 30.62382485])

array([24.9613063 , 21.28692715, 29.02550097, 25.62324316, 30.62382485])

## Create a vector of ones the same size as your BMI vector using `np.ones()`

In [18]:
# Your code here
identity = np.ones(5)
identity

array([1., 1., 1., 1., 1.])

## Multiply the BMI_array by your vector of ones
The resulting product should have the same values as your original BMI numpy array.

In [19]:
# Your code here
results = np.multiply(BMI_array,identity)
results

array([24.9613063 , 21.28692715, 29.02550097, 25.62324316, 30.62382485])

## Level Up: Using NumPy to Parse a File
The Pandas library that we've been using is built on top of NumPy; all columns/series in a Pandas DataFrame are built using NumPy arrays. To get a better idea of a how a built-in method like `pd.read_csv()` works, we'll try and recreate that here!

In [20]:
# Open a text file (csv files are just plaintext separated by commas)
f = open('bp.txt')
n_rows = len(f.readlines())
# Print number of lines in the file
print('The file has {} lines.'.format(n_rows)) 
# After using readlines, we must reopen the file
f = open('bp.txt') 
# The file has values separated by tabs; we read the first line and check it's length 
n_cols = (len(f.readline().split('\t'))) 

f = open('bp.txt')

# Your code here
import pandas as pd

df =pd.read_csv('bp.txt')
df
# Pseudocode outline below
#1) Create a matrix of zeros that is the same size of the file
#2) Iterate through the file: "for line in f:" Hint: using enumerate will also be required
    #3) Update each row of the matrix with the new stream of data
    #Hint: skip the first row (it's just column names, not the data.)
#4) Preview your results; you should now have a NumPy matrix with the data from the file


The file has 21 lines.


Pt\tBP\tAge\tWeight\tBSA\tDur\tPulse\tStress
0           1\t105\t47\t85.4\t1.75\t5.1\t63\t33
1           2\t115\t49\t94.2\t2.10\t3.8\t70\t14
2           3\t116\t49\t95.3\t1.98\t8.2\t72\t10
3           4\t117\t50\t94.7\t2.01\t5.8\t73\t99
4           5\t112\t51\t89.4\t1.89\t7.0\t72\t95
5           6\t121\t48\t99.5\t2.25\t9.3\t71\t10
6           7\t121\t49\t99.8\t2.25\t2.5\t69\t42
7            8\t110\t47\t90.9\t1.90\t6.2\t66\t8
8           9\t110\t49\t89.2\t1.83\t7.1\t69\t62
9          10\t114\t48\t92.7\t2.07\t5.6\t64\t35
10         11\t114\t47\t94.4\t2.07\t5.3\t74\t90
11         12\t115\t49\t94.1\t1.98\t5.6\t71\t21
12        13\t114\t50\t91.6\t2.05\t10.2\t68\t47
13         14\t106\t45\t87.1\t1.92\t5.6\t67\t80
14       15\t125\t52\t101.3\t2.19\t10.0\t76\t98
15         16\t114\t46\t94.5\t1.98\t7.4\t69\t95
16         17\t106\t46\t87.0\t1.87\t3.6\t62\t18
17         18\t113\t46\t94.5\t1.90\t4.3\t70\t12
18         19\t110\t48\t90.5\t1.88\t9.0\t71\t99
19         20\t122\t56\t95.7\t2.09\t7.0\t75\t99

Here’s a breakdown of the steps based on your pseudocode:

* Create a matrix of zeros with the same dimensions as the file. This means we first need to know the number of rows and columns in the file.
* Read the file line by line, skipping the first line (which contains the column headers).
* Update each row in the matrix with the data from the file.
* Preview the results.

In [21]:
import pandas as pd
import numpy as np

# Open the file and calculate the number of rows and columns
f= open('bp.txt')

# Read all lines in the file
lines = f.readlines()
n_rows = len(lines) - 1  # Subtract 1 to exclude the header row
n_cols = len(lines[0].split('\t'))  # Assuming data is tab-separated

# Create a matrix of zeros with the same dimensions as the file
data_matrix = np.zeros((n_rows, n_cols))

# Reopen the file and skip the header row (first line)
f= open('bp.txt')

# Skip the header row
next(f)

# Iterate through the file, line by line
for i, line in enumerate(f):
    # Split the line by tab character and convert it to a list of values
    row_data = line.strip().split('\t')
    
    # Update the matrix (convert row data to numeric values and update the matrix)
    data_matrix[i] = np.array(row_data, dtype=float)

# Preview the result matrix
#print(data_matrix)

# If you want to convert it to a pandas DataFrame for easier visualization:
df = pd.DataFrame(data_matrix)
print(df)


       0      1     2      3     4     5     6     7
0    1.0  105.0  47.0   85.4  1.75   5.1  63.0  33.0
1    2.0  115.0  49.0   94.2  2.10   3.8  70.0  14.0
2    3.0  116.0  49.0   95.3  1.98   8.2  72.0  10.0
3    4.0  117.0  50.0   94.7  2.01   5.8  73.0  99.0
4    5.0  112.0  51.0   89.4  1.89   7.0  72.0  95.0
5    6.0  121.0  48.0   99.5  2.25   9.3  71.0  10.0
6    7.0  121.0  49.0   99.8  2.25   2.5  69.0  42.0
7    8.0  110.0  47.0   90.9  1.90   6.2  66.0   8.0
8    9.0  110.0  49.0   89.2  1.83   7.1  69.0  62.0
9   10.0  114.0  48.0   92.7  2.07   5.6  64.0  35.0
10  11.0  114.0  47.0   94.4  2.07   5.3  74.0  90.0
11  12.0  115.0  49.0   94.1  1.98   5.6  71.0  21.0
12  13.0  114.0  50.0   91.6  2.05  10.2  68.0  47.0
13  14.0  106.0  45.0   87.1  1.92   5.6  67.0  80.0
14  15.0  125.0  52.0  101.3  2.19  10.0  76.0  98.0
15  16.0  114.0  46.0   94.5  1.98   7.4  69.0  95.0
16  17.0  106.0  46.0   87.0  1.87   3.6  62.0  18.0
17  18.0  113.0  46.0   94.5  1.90   4.3  70.0

## Summary

In this lab, we practiced creating NumPy arrays from both lists and ranges. We then practiced performing math operations like converting imperial measurements to metric measurements on each element of a NumPy array to create new arrays with new values. Finally, we used both of our new NumPy arrays to operate on each other and create new arrays containing the BMIs from our arrays containing heights and weights.